version: '3'

services:
    app:
        build:
            context: node
        container_name: app
        networks:
            - node_network
        volumes: 
            - ./node:/usr/src/app
        tty: true
        ports:
            - 3000:3000

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
            # - MYSQL_USER=root #Pode ser apagada, nas versoes mais novas da imagem o usuario root já é criado por padrão
        networks:
            - node_network

networks:
    node_network:
        driver: bridge