FROM php:7.4-cli

WORKDIR /var/www

RUN apt-get update && \
    apt-get install -y libzip-dev zip && \
    docker-php-ext-install zip

#Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

#Install Laravel
RUN composer create-project --prefer-dist laravel/laravel:8.0 laravel

#Run artisan serve
ENTRYPOINT ["php", "laravel/artisan", "serve"]

CMD ["--host=0.0.0.0"]